package fu.client;

import com.google.gwt.user.client.ui.FormPanel;
import com.google.gwt.user.client.ui.Grid;
import com.google.gwt.user.client.ui.Label;
import com.google.gwt.user.client.ui.TextBox;

public class Form {
	public static Label bootsnameLabel = new Label("Bootsname");
	public static Label registernrLabel = new Label("Registernr");
	public static Label segelzeichenLabel = new Label("Segelzeichen");
	public static Label heimathafenLabel = new Label("Heimathafen");
	public static Label yachtclubLabel = new Label("Yachtclub");
	public static Label eignerLabel = new Label("Eigner");
	public static Label versicherungLabel = new Label("Versicherung");
	public static Label rufzeichenLabel = new Label("Rufzeichen");
	public static Label typLabel = new Label("Typ");
	public static Label konstrukteurLabel = new Label("Konstrukteur");
	public static Label laengeLabel = new Label("Laenge");
	public static Label breiteLabel = new Label("Breite");
	public static Label tiefgangLabel = new Label("Tiefgang");
	public static Label masthoeheLabel = new Label("Masthoehe");
	public static Label verdraengungLabel = new Label("Verdraengung");
	public static Label rigartLabel = new Label("Rigart");
	public static Label baujahrLabel = new Label("Baujahr");
	public static Label motorLabel = new Label("Motor");
	public static Label tankgroesseLabel = new Label("Tankgroesse");
	public static Label wassertankgroesseLabel = new Label("Wassertankgroesse");
	public static Label abwassertankgroesseLabel = new Label(
			"Abwassertankgroesse");
	public static Label grosssegelgroesseLabel = new Label("Grosssegelgroesse");
	public static Label genuaLabel = new Label("Genua");
	public static Label spiLabel = new Label("Spi Size Groesse");
	public static TextBox bootsnameBox = new TextBox();
	public static TextBox registernrBox = new TextBox();
	public static TextBox segelzeichenBox = new TextBox();
	public static TextBox heimathafenBox = new TextBox();
	public static TextBox yachtclubBox = new TextBox();
	public static TextBox eignerBox = new TextBox();
	public static TextBox versicherungBox = new TextBox();
	public static TextBox rufzeichenBox = new TextBox();
	public static TextBox typBox = new TextBox();
	public static TextBox konstrukteurBox = new TextBox();
	public static TextBox laengeBox = new TextBox();
	public static TextBox breiteBox = new TextBox();
	public static TextBox tiefgangBox = new TextBox();
	public static TextBox masthoehBox = new TextBox();
	public static TextBox verdraengungBox = new TextBox();
	public static TextBox rigartBox = new TextBox();
	public static TextBox baujahrBox = new TextBox();
	public static TextBox motorBox = new TextBox();
	public static TextBox tankgroesseBox = new TextBox();
	public static TextBox wassertankgroesseBox = new TextBox();
	public static TextBox abwassertankgroesseBox = new TextBox();
	public static TextBox grosssegelgroesseBox = new TextBox();
	public static TextBox genuaBox = new TextBox();
	public static TextBox spiBox = new TextBox();
	public static Grid grid = new Grid(9, 6);
	public static FormPanel form;
	private MyHandler handler;

	public FormPanel initForm() {
		handler = new MyHandler();
		form = new FormPanel();
		grid.setWidget(0, 0, bootsnameLabel);
		grid.setWidget(1, 0, registernrLabel);
		grid.setWidget(2, 0, segelzeichenLabel);
		grid.setWidget(3, 0, heimathafenLabel);
		grid.setWidget(4, 0, yachtclubLabel);
		grid.setWidget(5, 0, eignerLabel);
		grid.setWidget(6, 0, versicherungLabel);
		grid.setWidget(7, 0, rufzeichenLabel);
		grid.setWidget(0, 2, typLabel);
		grid.setWidget(1, 2, konstrukteurLabel);
		grid.setWidget(2, 2, laengeLabel);
		grid.setWidget(3, 2, breiteLabel);
		grid.setWidget(4, 2, tiefgangLabel);
		grid.setWidget(5, 2, masthoeheLabel);
		grid.setWidget(6, 2, verdraengungLabel);
		grid.setWidget(7, 2, rigartLabel);
		grid.setWidget(0, 4, baujahrLabel);
		grid.setWidget(1, 4, motorLabel);
		grid.setWidget(2, 4, tankgroesseLabel);
		grid.setWidget(3, 4, wassertankgroesseLabel);
		grid.setWidget(4, 4, abwassertankgroesseLabel);
		grid.setWidget(5, 4, grosssegelgroesseLabel);
		grid.setWidget(6, 4, genuaLabel);
		grid.setWidget(7, 4, spiLabel);
		grid.setWidget(0, 1, bootsnameBox);
		grid.setWidget(1, 1, registernrBox);
		grid.setWidget(2, 1, segelzeichenBox);
		grid.setWidget(3, 1, heimathafenBox);
		grid.setWidget(4, 1, yachtclubBox);
		grid.setWidget(5, 1, eignerBox);
		grid.setWidget(6, 1, versicherungBox);
		grid.setWidget(7, 1, rufzeichenBox);
		grid.setWidget(0, 3, typBox);
		grid.setWidget(1, 3, konstrukteurBox);
		grid.setWidget(2, 3, laengeBox);
		grid.setWidget(3, 3, breiteBox);
		grid.setWidget(4, 3, tiefgangBox);
		grid.setWidget(5, 3, masthoehBox);
		grid.setWidget(6, 3, verdraengungBox);
		grid.setWidget(7, 3, rigartBox);
		grid.setWidget(0, 5, baujahrBox);
		grid.setWidget(1, 5, motorBox);
		grid.setWidget(2, 5, tankgroesseBox);
		grid.setWidget(3, 5, wassertankgroesseBox);
		grid.setWidget(4, 5, abwassertankgroesseBox);
		grid.setWidget(5, 5, grosssegelgroesseBox);
		grid.setWidget(6, 5, genuaBox);
		grid.setWidget(7, 5, spiBox);
		bootsnameBox.setTabIndex(1);
		registernrBox.setTabIndex(2);
		segelzeichenBox.setTabIndex(3);
		heimathafenBox.setTabIndex(4);
		yachtclubBox.setTabIndex(5);
		eignerBox.setTabIndex(6);
		versicherungBox.setTabIndex(7);
		rufzeichenBox.setTabIndex(8);
		typBox.setTabIndex(9);
		konstrukteurBox.setTabIndex(10);
		laengeBox.setTabIndex(11);
		breiteBox.setTabIndex(12);
		tiefgangBox.setTabIndex(13);
		masthoehBox.setTabIndex(14);
		verdraengungBox.setTabIndex(15);
		rigartBox.setTabIndex(16);
		baujahrBox.setTabIndex(17);
		motorBox.setTabIndex(18);
		tankgroesseBox.setTabIndex(19);
		wassertankgroesseBox.setTabIndex(20);
		abwassertankgroesseBox.setTabIndex(21);
		grosssegelgroesseBox.setTabIndex(22);
		genuaBox.setTabIndex(23);
		spiBox.setTabIndex(24);
		bootsnameBox.addKeyUpHandler(handler);
		registernrBox.addKeyUpHandler(handler);
		segelzeichenBox.addKeyUpHandler(handler);
		heimathafenBox.addKeyUpHandler(handler);
		yachtclubBox.addKeyUpHandler(handler);
		eignerBox.addKeyUpHandler(handler);
		versicherungBox.addKeyUpHandler(handler);
		rufzeichenBox.addKeyUpHandler(handler);
		typBox.addKeyUpHandler(handler);
		konstrukteurBox.addKeyUpHandler(handler);
		laengeBox.addKeyUpHandler(handler);
		breiteBox.addKeyUpHandler(handler);
		tiefgangBox.addKeyUpHandler(handler);
		masthoehBox.addKeyUpHandler(handler);
		verdraengungBox.addKeyUpHandler(handler);
		rigartBox.addKeyUpHandler(handler);
		baujahrBox.addKeyUpHandler(handler);
		motorBox.addKeyUpHandler(handler);
		tankgroesseBox.addKeyUpHandler(handler);
		wassertankgroesseBox.addKeyUpHandler(handler);
		abwassertankgroesseBox.addKeyUpHandler(handler);
		grosssegelgroesseBox.addKeyUpHandler(handler);
		genuaBox.addKeyUpHandler(handler);
		spiBox.addKeyUpHandler(handler);
		form.add(grid);
		return form;
	}

	public void reset_form() {
		bootsnameBox.setText("");
		registernrBox.setText("");
		segelzeichenBox.setText("");
		heimathafenBox.setText("");
		yachtclubBox.setText("");
		eignerBox.setText("");
		versicherungBox.setText("");
		rufzeichenBox.setText("");
		typBox.setText("");
		konstrukteurBox.setText("");
		laengeBox.setText("");
		breiteBox.setText("");
		tiefgangBox.setText("");
		masthoehBox.setText("");
		verdraengungBox.setText("");
		rigartBox.setText("");
		baujahrBox.setText("");
		motorBox.setText("");
		tankgroesseBox.setText("");
		wassertankgroesseBox.setText("");
		abwassertankgroesseBox.setText("");
		grosssegelgroesseBox.setText("");
		genuaBox.setText("");
		spiBox.setText("");
	}

	public void set_form(BoatDTO boat) {
		bootsnameBox.setText(boat.bootsname);
		registernrBox.setText(boat.registernr);
		segelzeichenBox.setText(boat.segelzeichen);
		heimathafenBox.setText(boat.heimathafen);
		yachtclubBox.setText(boat.yachtclub);
		eignerBox.setText(boat.eigner);
		versicherungBox.setText(boat.versicherung);
		rufzeichenBox.setText(boat.rufzeichen);
		typBox.setText(boat.typ);
		konstrukteurBox.setText(boat.konstrukteur);
		laengeBox.setText(String.valueOf(boat.laenge));
		breiteBox.setText(String.valueOf(boat.breite));
		tiefgangBox.setText(String.valueOf(boat.tiefgang));
		masthoehBox.setText(String.valueOf(boat.masthoehe));
		verdraengungBox.setText(String.valueOf(boat.verdraengung));
		rigartBox.setText(boat.rigart);
		baujahrBox.setText(String.valueOf(boat.baujahr));
		motorBox.setText(boat.motor);
		tankgroesseBox.setText(String.valueOf(boat.tankgroesse));
		wassertankgroesseBox.setText(String.valueOf(boat.wassertankgroesse));
		abwassertankgroesseBox
				.setText(String.valueOf(boat.abwassertankgroesse));
		grosssegelgroesseBox.setText(String.valueOf(boat.grosssegelgroesse));
		genuaBox.setText(String.valueOf(boat.genaugroesse));
		spiBox.setText(String.valueOf(boat.spi));
	}
}